### ISSUE TITLE
Missing Illusions 'Reflection'

### ISSUE THREAD

**Issue by jameskurtak** [lauraW522/defenses#1]
Hi first of all - great work! This is really awesome. However I was messing around with this yesterday and noticed you had not included reflection (though perhaps this is due to it being removed after every hit?)

That said, this is really really awesome work! Saved me so much time making triggers on my own and even caught some defences I didn't even know I had!

**Comment by lauraW522** [comment]
Thank you! I can add that one in, though it won't be one that's attempted
to be unkept. Sounds like just an oversight, I rarely play classes that use
it.

**Comment by lauraW522** [comment]
This has been added, you can download the latest version or download the release I made, they're identical.

**Comment by jameskurtak** [comment]
Wow! Thank you, that was an amazing turn around! I'm glad that I don't have to put it in myself (haha) though I'll definitely do a diff to see exactly how you added a new defense. If I find a new defense that isn't included I'll be happy to add it myself and do a merge request.

Thank you!

**Comment by lauraW522** [comment]
Absolutely! Adding new defenses is simple. Create a new entry in the
defense_database script with the name of the defense and all the other
information filled out like the other entries. IE:
ablution = {
name = "ablution",
active = false,
auto = false,
pow = 2,
enabled = true,
req = {"eq","bal"},
use = {"eq"},
skill = "sacraments",
initial = "combat",
cmd = "starchant ablution"
}, And put it in alphabetical order. Then add the trigger for raising the
defense and for losing it, if one exists. updateDefenses("ablution",true)
means the defense is raised, while false means it's lost. Log out, log back
in, and everything else should work fine.

**Comment by jameskurtak** [comment]
Wow thanks Laura! Again, exactly what I need :)
